#2014382: added "X Remaining conflicts" label in the merge dialog
aditosoftware/adito-nb-git pull request #213
Opened 2023-01-16 11:52 UTC by rH4rtinger

2023-01-17 10:15 UTC, L1nc0ln requested changes

2023-01-17 10:15 UTC, L1nc0ln commented on gui/src/main/java/de/adito/git/gui/tablemodels/MergeDiffStatusModel.java
> +    addTableModelListener(e -> remainingConflicts.setText(MessageFormat.format("{0} remaining conflicts", getRowCount())));
you should be able to add the tableModelListener from the MergeConflictDialog, thus negating the need to pass the remainingConflicts label to this TableModel

2023-01-17 13:12 UTC, rH4rtinger commented on gui/src/main/java/de/adito/git/gui/tablemodels/MergeDiffStatusModel.java
> +    addTableModelListener(e -> remainingConflicts.setText(MessageFormat.format("{0} remaining conflicts", getRowCount())));
listener is now removed from the model and added to the model in the MergeConflictDialog class

2023-01-18 08:17 UTC, L1nc0ln approved these changes

2023-01-18 09:16 UTC, merged