feat: reworked the way the lineNumbers and colored areas are calculat…
aditosoftware/adito-nb-git pull request #214
Opened 2023-01-17 12:25 UTC by L1nc0ln

…ed, leading to a big increase in both performance and memory consumption

2023-01-18 09:15 UTC, rH4rtinger requested changes

2023-01-18 09:15 UTC, rH4rtinger commented on gui/src/test/java/de/adito/git/gui/dialogs/panels/basediffpanel/diffpane/LineChangeMarkingModelTest.java
> +  void isCorrectLineNumberColorsWhenSingleDelete()
see my comment above for empty new lines, order of lines, asserts.

Also you might want to move the same parts of this method and `isCorrectLineNumberColorsWhenSingleModify` to an extra method

2023-01-18 09:15 UTC, rH4rtinger commented on gui/src/test/java/de/adito/git/gui/dialogs/panels/basediffpanel/diffpane/LineChangeMarkingModelTest.java
> +  void isCorrectLineNumberColorsWhenSingleInsert()
see my comments above for empty new lines, order of lines, asserts and same parts.

2023-01-18 09:15 UTC, rH4rtinger commented on gui/src/test/java/de/adito/git/gui/dialogs/panels/basediffpanel/diffpane/LineChangeMarkingModelTest.java
> +  void isCorrectLineNumberColorsWhenMultiChange()
see my comments above for empty new lines, order of lines, asserts and same parts.

2023-01-18 09:15 UTC, rH4rtinger commented on gui/src/test/java/de/adito/git/gui/dialogs/panels/basediffpanel/diffpane/LineNumberModelTest.java
> +  private static LineNumberModel setUpLineNumberModelTest(@NotNull AtomicReference<IDeltaTextChangeEvent> textEventRef, @NotNull AtomicReference<LineNumber[]> lineNumbersRef,
javadoc is missing throws exceptions.

2023-01-18 09:15 UTC, rH4rtinger commented on gui/src/test/java/de/adito/git/gui/dialogs/panels/basediffpanel/diffpane/LineNumberModelTest.java
> +   * @param mockStatic     Reference for the static mock of the TextPaneUtil, will be set in this method and has to be closed by the caller to avoid resource leaks
if I remember correctly, you are passing a mockStatic to your method, because you could not mock it directly in the main thread because of some problems. If this is correct, you should tell this in your javadoc.

2023-01-18 09:15 UTC, rH4rtinger commented on gui/src/test/java/de/adito/git/gui/dialogs/panels/basediffpanel/diffpane/LineNumberModelTest.java
> +      assertArrayEquals(lineNumbers, lineNumbersRef.get());
A empty line above your asserts will improve the readability.
Also if you three assert does not depend on each other, you can put them inside an `assertAll`.
The advantage of `assertAll `is, that all the assertions in there are executed and you will get all the failures, whereas with multiple asserts below each other the execution of those will stop after the first failure and you will not be informed if another of the assertions will also fail.

2023-01-18 09:15 UTC, rH4rtinger commented on gui/src/test/java/de/adito/git/gui/dialogs/panels/basediffpanel/diffpane/LineNumberModelTest.java
> +      assertArrayEquals(lineNumbers, lineNumbersRef.get());
A empty line above your asserts will improve the readability.
Also if you three assert does not depend on each other, you can put them inside an `assertAll`.
The advantage of `assertAll `is, that all the assertions in there are executed and you will get all the failures, whereas with multiple asserts below each other the execution of those will stop after the first failure and you will not be informed if another of the assertions will also fail.

2023-01-18 09:15 UTC, rH4rtinger commented on gui/src/test/java/de/adito/git/gui/dialogs/panels/basediffpanel/diffpane/LineNumberModelTest.java
> +  {
new empty lines for improving readability after lines 105, 110, 116
Switch Lines 112 and 111.

2023-01-18 09:15 UTC, rH4rtinger commented on gui/src/test/java/de/adito/git/gui/dialogs/panels/basediffpanel/diffpane/ViewLineChangeMarkingModelTest.java
> +    assertEquals(List.of(), viewLineChangeMarkingModel.getLineNumberColors());
For better readability:
Move line 30 at the start of the method, followed by a new line.
New lines after 31, 33, 35

2023-01-18 09:15 UTC, rH4rtinger commented on gui/src/test/java/de/adito/git/gui/dialogs/panels/basediffpanel/diffpane/ViewLineChangeMarkingModelTest.java
> +  void isValueCorrectWithOffsetViewArea()
for better readability see comment above.

You have some identical parts with the `isEmptyListReturnedWhenNoColorsExist`. You might want to move the same parts to another method.


Also if your assert does not depend on each other, you can put them inside an `assertAll`.
The advantage of `assertAll `is, that all the assertions in there are executed and you will get all the failures, whereas with multiple asserts below each other the execution of those will stop after the first failure and you will not be informed if another of the assertions will also fail.

2023-01-18 09:15 UTC, rH4rtinger commented on gui/src/test/java/de/adito/git/gui/dialogs/panels/basediffpanel/diffpane/ViewLineChangeMarkingModelTest.java
> +  void isValueAdjustedAfterScroll()
see comment above for new lines, order, asserts and same parts.

Of course, in this case you can have two assertAlls. One for Lines 69,70 and one for lines 73,74.
Also a new line above your comment in line 71 will additionally improve the readability

2023-01-18 09:15 UTC, rH4rtinger commented on gui/src/test/java/de/adito/git/gui/dialogs/panels/basediffpanel/diffpane/ViewLineChangeMarkingModelTest.java
> +  void isValuesCorrectWithOffsetViewArea()
see above for new lines, order, same parts, assertAll.

2023-01-18 09:15 UTC, rH4rtinger commented on gui/src/test/java/de/adito/git/gui/dialogs/panels/basediffpanel/diffpane/ViewLineChangeMarkingModelTest.java
> +  void isValuesAdjustedAfterScroll()
see above for new lines, order, same parts, assertAll

2023-01-19 08:00 UTC, L1nc0ln commented on gui/src/main/java/de/adito/git/gui/dialogs/panels/basediffpanel/diffpane/IconInfoModel.java
> +    TreeMap<Integer, IconInfo> tmp = discardCoordinateMapping;
Basically, the new variable is for threadsafety. I do not create a new reference via a new TreeMap because I do not want to create the Map again, and the discardCoordinateMapping gets a new reference if it changes, thus negating the need for creating a new map here.

2023-01-19 08:24 UTC, L1nc0ln commented on gui/src/main/java/de/adito/git/gui/dialogs/panels/basediffpanel/diffpane/IconInfoModel.java
> +        .map(pRectangle -> pRectangle.y + pRectangle.height >= pYStart)
That would require casting the result of getX and getHeight

2023-01-19 08:25 UTC, L1nc0ln commented on gui/src/main/java/de/adito/git/gui/dialogs/panels/basediffpanel/diffpane/IconInfoModel.java
> +      map.put(iconInfo.getIconCoordinates().y, iconInfo);
Would require casting again, because getY returns a double

2023-01-20 10:28 UTC, rH4rtinger requested changes

2023-01-20 10:28 UTC, rH4rtinger commented on gui/src/main/java/de/adito/git/gui/dialogs/panels/basediffpanel/diffpane/LineNumberModel.java
> +        Logger.getLogger(LineNumberModel.class.getName()).log(Level.WARNING, pE, () -> "Git Plugin: Could not calculate LineNumber coordinates");
You might want to add a logger as a `static final` field in the class. This can be done via normal java or via Lombok and the annotation `@Log`. 

Either way, this will allow others to easily use the logger in other methods of the class, without needing to get the logger once more.

2023-01-20 10:28 UTC, rH4rtinger commented on gui/src/main/java/de/adito/git/gui/dialogs/panels/basediffpanel/diffpane/LineChangeMarkingModel.java
> +      Logger.getLogger(LineChangeMarkingModel.class.getName()).log(Level.WARNING, pE, () -> "Git Plugin: Could not calculate LineNumberColors");
You might want to add a logger as a `static final` field in the class. This can be done via normal java or via Lombok and the annotation `@Log`. 

Either way, this will allow others to easily use the logger in other methods of the class, without needing to get the logger once more.

2023-01-20 10:28 UTC, rH4rtinger commented on gui/src/main/java/de/adito/git/gui/dialogs/panels/basediffpanel/diffpane/ListenableModel.java
> +public class ListenableModel<T>
As this is a base class, it could also be `abstract`, if there are no implementations.

Also javadoc for parameter `<T>` is missing

2023-01-20 10:28 UTC, rH4rtinger commented on gui/src/main/java/de/adito/git/gui/dialogs/panels/basediffpanel/diffpane/ListenableModel.java
> +  protected List<T> listenerList = new ArrayList<>();
I'm not completely happy with the name `listenerList`.
I would rather name it `listeners`.

By having the name `listenerList`, it tells others that they should expect a list. But if you change the type of the list to e.g. a `Set`, the name may not be changed can be therefore missleading.
With having the name `listeners`, the plural s indicates that there are more objects coming.

2023-01-20 10:28 UTC, rH4rtinger commented on gui/src/main/java/de/adito/git/gui/dialogs/panels/basediffpanel/diffpane/ListenableModel.java
> +  protected List<T> listenerList = new ArrayList<>();
As I am seeing from the usages of you listeners, you have two places in all your 4 implemented classes. These can be improved.
* `discard` -> you could add a method `discardListeners` to this calls and call it instead of ` listenerList.clear();` in the subclasses
* `notifyListeners` -> add a protected method `notifyListeners` to this class and a abstract method with the action (names are up to discussion)
```
  abstract Consumer<T> getForEachAction();

  protected void notifyListeners()
  {
    listenerList.forEach(getForEachAction());
  }
```


=> if you change these things, you can make your field private again and do not need it to call in you subclasses.

2023-01-20 10:28 UTC, rH4rtinger commented on gui/src/test/java/de/adito/git/gui/dialogs/panels/basediffpanel/diffpane/IconInfoModelTest.java
> +  public static Stream<Arguments> singleModificationSource()
The method can be `private` if the arguments are not used in another class.
Javadoc is missing.

2023-01-20 10:28 UTC, rH4rtinger commented on gui/src/test/java/de/adito/git/gui/dialogs/panels/basediffpanel/diffpane/IconInfoModelTest.java
> +  void test(@NotNull String pOldVersion, @NotNull String pNewVersion)
maybe change the method name to something better than `test`?

2023-01-20 10:28 UTC, rH4rtinger commented on gui/src/test/java/de/adito/git/gui/dialogs/panels/basediffpanel/diffpane/LineChangeMarkingModelTest.java
> +  private static LineChangeMarkingModel getLineChangeMarkingModel(@NotNull LineNumber[] pLineNumbers, @NotNull String pOldVersion, @NotNull String pNewVersion)
javadoc is missing

2023-01-20 11:24 UTC, L1nc0ln commented on gui/src/main/java/de/adito/git/gui/dialogs/panels/basediffpanel/diffpane/ListenableModel.java
> +  protected List<T> listenerList = new ArrayList<>();
I like the discard listeners method, however I am not entirely sure how the notifyListeners method should work, as the listeners have from 0 to 2 different parameters, so nothing I can replace with a simple generic term

2023-01-23 06:06 UTC, rH4rtinger requested changes

2023-01-23 06:06 UTC, rH4rtinger commented on gui/src/main/java/de/adito/git/gui/dialogs/panels/basediffpanel/diffpane/LineNumPanel.java
> +  private static final int SAFETY_MARGIN_Y = 32;
a new empty  line after you static fields will improve the readability

2023-01-23 07:15 UTC, rH4rtinger approved these changes

2023-01-23 07:32 UTC, merged